name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Get leiningen
      run: brew install leiningen
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Create uberjar
      run: lein uberjar
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '20.0.0.java11'
    - name: Install native-image
      run: gu install native-image
    - name: Compile uberjar into native-image
      run: native-image -jar target/native-clj-cli-0.1.0-SNAPSHOT-standalone.jar -H:Name=native-clj-cli -H:+ReportExceptionStackTraces -H:+ReportUnsupportedElementsAtRuntime --initialize-at-build-time --verbose --no-fallback --no-server "-J-Xmx3g"
    - name: Test native executable
      run: ./native-clj-cli --help
    - name: Save native executable as artifact
      uses: actions/upload-artifact@v1
      with:
        name: native-clj-cli
        path: ./native-clj-cli
